import {
  OpenAPIRegistry,
  OpenApiGeneratorV3,
  extendZodWithOpenApi,
} from '@asteasolutions/zod-to-openapi'
import { z } from 'zod'

import { registerNotifications } from '@/api/v1/notifications/notifications.openapi'
import registerAuth from '@/api/v1/auth/auth.openapi'
import registerCart from '@/api/v1/cart/cart.openapi'
import { registerUsers } from './api/v1/users/users.openapi'
import { registerCategories } from './api/v1/categories/categories.openapi'
import { registerOrders } from './api/v1/orders/orders.openapi'
import { registerPayment } from './api/v1/payment/payment.openapi'
import { registerProducts } from './api/v1/products/products.openapi'
import { registerReviews } from './api/v1/reviews/reviews.openapi'

extendZodWithOpenApi(z)

const globalRegistry = new OpenAPIRegistry()

registerAuth(globalRegistry)
registerUsers(globalRegistry)
registerCategories(globalRegistry)
registerProducts(globalRegistry)
registerOrders(globalRegistry)
registerCart(globalRegistry)
registerReviews(globalRegistry)
registerPayment(globalRegistry)
registerNotifications(globalRegistry)

const generator = new OpenApiGeneratorV3(globalRegistry.definitions)

const openApiDocument = generator.generateDocument({
  openapi: '3.0.0',
  info: {
    title: 'ex-mark1 API Docs',
    version: '1.0.0',
    description: 'Autogenerated OpenAPI spec from Zod schemas',
  },
  servers: [{ url: process.env.APP_BASE_URL! }],
  security: [
    {
      BearerAuth: [],
    },
  ],
  tags: [
    {
      name: 'Authentication',
      description: 'Authentication management endpoints',
    },
    { name: 'Users', description: 'User management endpoints' },
    { name: 'Cart', description: 'Cart operations' },
    { name: 'Orders', description: 'Order processing endpoints' },
    { name: 'Products', description: 'Product catalog endpoints' },
    { name: 'Categories', description: 'Category management endpoints' },
    { name: 'Reviews', description: 'Product review endpoints' },
    { name: 'Payment', description: 'Payment processing endpoints' },
    { name: 'Notifications', description: 'Notification management endpoints' },
  ],
})

openApiDocument.components = {
  ...openApiDocument.components,
  securitySchemes: {
    BearerAuth: {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT',
    },
  },
}

export { openApiDocument }
